/** Copy for the unified energy balance, BIPV incremental economics and the Google Solar benchmark. */
const en = {
  coverage: "Household Solar Coverage",
  coverageShort: "Solar coverage",
  chainDetail: (coverage: number, self: number, battery: boolean) => `${coverage}% of annual demand met by the solar system${battery ? " (direct + storage)" : " directly"} · PV self-consumption ${self}%.`,
  pvUsed: "Solar used at home",
  pvUsedDetail: (direct: string, battery: string | null) => battery ? `Direct ${direct} + from battery ${battery} kWh` : `Direct use ${direct} kWh`,
  selfRate: (n: number) => `PV self-consumption ${n}%`,
  exportRate: (n: number) => `Export rate ${n}%`,
  direct: "Direct PV to home",
  directDetail: "Used the moment it is generated",
  batteryToLoad: "Battery to home (solar)",
  batteryToLoadOn: "Stored solar delivered later in the day",
  batteryToLoadOff: "Choose solar + battery to model storage",
  gridImport: "Grid import",
  scenarioRow: (label: string, coverage: number, self: number) => `${label}: coverage ${coverage}% · self-consumption ${self}%`,
  solarOnly: "Solar only",
  withBattery: (kwh: string) => `Solar + ${kwh} kWh battery`,
  battery: "Battery",
  batteryValue: (kwh: string, rec: string, auto: boolean) => auto ? `${kwh} kWh (recommended)` : `${kwh} kWh (custom · recommended ${rec} kWh)`,
  editBattery: "Change battery capacity",
  investment: "BIPV incremental investment",
  payback: "Incremental payback",
  years: (y: string) => `${y} years`,
  noPayback: "Beyond 25 years",
  formula: (pv: string, conv: string, spec: string) => `PV products ${pv} − conventional products ${conv} + PV-specific ${spec}`,
  plusBattery: (b: string) => `+ battery ${b}`,
  annualBenefit: "Annual benefit (bill saving + export income)",
  economicsNote: "Labour, installation, scaffolding and roofing happen with conventional tiles too, so they are excluded from the PV investment. Payback = incremental investment ÷ annual benefit.",
  paybackLine: (inv: string, y: string) => `Incremental investment ${inv} · incremental payback ${y}`,
  cashBreakEven: (y: number) => `Cumulative cash positive in year ${y}`,
  googleTitle: "External Roof & Solar Benchmark — Google Solar",
  googleLabel: "Traditional monocrystalline PV benchmark",
  googleLayout: "Traditional panels (benchmark)",
  googleLayoutValue: (p: number, k: string) => `${p} panels · ${k} kWp`,
  googleYearly: "Traditional mono-Si yearly (benchmark)",
  moderniteLine: "Modernite BIPV (this study)",
  moderniteValue: (area: string, kwp: string, kwh: string) => `${area} m² · ${kwp} kWp · ${kwh} kWh/yr`,
  compareTitle: "Like-for-like comparison",
  colMetric: "Metric",
  perKwp: "kWh / kWp",
  perM2: "kWh / m²",
  googleNote: "Google data cross-checks roof geometry, pitch, orientation and sunshine, and gives a traditional monocrystalline benchmark. Modernite tiles, area, kWp and generation come from this study's BIPV engine. Google's DC figure is converted with the same 90% AC factor used here; weather periods may differ.",
  ledgerCosts: (inc: string, pv: string, conv: string, spec: string, battery: string | null, est: boolean) => `${inc} = PV products ${pv} − conventional ${conv} + PV-specific ${spec}${battery ? ` · battery ${battery}` : ""}${est ? " · indicative" : ""}`,
  ledgerCostsLabel: "BIPV incremental investment",
  // Energy page
  batteryAuto: (rec: string | null) => rec ? `Defaults to the recommended ${rec} kWh (last calculation); edit to override.` : "Defaults to the recommended capacity, matched to your final design and demand when you calculate; edit to override.",
  batteryRecommended: "Recommended",
  useRecommended: "Use recommended",
  pvProductPrice: "Modernite PV product quote",
  conventionalPrice: "Conventional tiles / cladding replaced",
  priceInputs: "Incremental investment inputs (optional)",
  priceNote: "Incremental investment = PV product − conventional product it replaces + PV-specific costs (inverter, connection). Common roofing works are excluded. Leave blank to use indicative prices.",
  previewCoverage: "Household Solar Coverage (last study)",
  previewInvestment: "BIPV incremental investment",
};

export type BipvCopy = typeof en;

const zh: BipvCopy = {
  coverage: "家庭光伏供电比例",
  coverageShort: "光伏供电比例",
  chainDetail: (c, s, b) => `年用电量的 ${c}% 由光伏系统满足${b ? "（直接 + 储能）" : "（光伏直接供电）"} · 光伏自消纳率 ${s}%。`,
  pvUsed: "家庭使用的光伏电",
  pvUsedDetail: (d, b) => b ? `直接 ${d} + 储能 ${b} kWh` : `光伏直接供电 ${d} kWh`,
  selfRate: (n) => `光伏自消纳率 ${n}%`,
  exportRate: (n) => `上网率 ${n}%`,
  direct: "光伏直接供家庭",
  directDetail: "发电当时即被家庭用掉",
  batteryToLoad: "储能供家庭（光伏来源）",
  batteryToLoadOn: "白天余电存入电池，晚间再供家庭",
  batteryToLoadOff: "选择“光伏 + 电池”以模拟储能",
  gridImport: "电网购电",
  scenarioRow: (l, c, s) => `${l}：供电比例 ${c}% · 自消纳率 ${s}%`,
  solarOnly: "仅光伏",
  withBattery: (k) => `光伏 + ${k} kWh 电池`,
  battery: "电池",
  batteryValue: (k, r, a) => a ? `${k} kWh（推荐容量）` : `${k} kWh（自定义 · 推荐 ${r} kWh）`,
  editBattery: "修改电池容量",
  investment: "BIPV 增量投资",
  payback: "增量回报期",
  years: (y) => `${y} 年`,
  noPayback: "超过 25 年",
  formula: (pv, conv, spec) => `光伏产品 ${pv} − 普通瓦/建材 ${conv} + 光伏专属 ${spec}`,
  plusBattery: (b) => `+ 电池 ${b}`,
  annualBenefit: "年度收益（节省电费 + 上网收益）",
  economicsNote: "人工、安装、脚手架和常规屋面施工在做普通瓦时同样会发生，不计入光伏增量投资。增量回报期 = 增量投资 ÷ 年度收益。",
  paybackLine: (inv, y) => `增量投资 ${inv} · 增量回报期 ${y}`,
  cashBreakEven: (y) => `第 ${y} 年累计现金流回正`,
  googleTitle: "Google Solar 屋顶与传统单晶硅参考模型 / External Roof & Solar Benchmark",
  googleLabel: "传统单晶硅光伏基准",
  googleLayout: "传统组件排板（基准）",
  googleLayoutValue: (p, k) => `${p} 块传统组件 · ${k} kWp`,
  googleYearly: "传统单晶硅年发电（基准）",
  moderniteLine: "Modernite BIPV（本研究）",
  moderniteValue: (a, k, e) => `${a} m² · ${k} kWp · ${e} kWh/年`,
  compareTitle: "同口径对比",
  colMetric: "指标",
  perKwp: "kWh / kWp",
  perM2: "kWh / m²",
  googleNote: "Google 数据用于交叉验证屋顶几何、坡度、朝向和日照，并作为传统单晶硅光伏基准；Modernite 光伏瓦数量、面积、kWp 和发电量由本研究的 BIPV 引擎计算。Google 的直流值已按本研究相同的 90% 交流系数换算；两者气象年份可能不同。",
  ledgerCosts: (inc, pv, conv, spec, battery, est) => `${inc} = 光伏产品 ${pv} − 普通瓦/建材 ${conv} + 光伏专属 ${spec}${battery ? ` · 电池 ${battery}` : ""}${est ? " · 指示性估算" : ""}`,
  ledgerCostsLabel: "BIPV 增量投资",
  batteryAuto: (r) => r ? `默认使用推荐容量 ${r} kWh（上次计算），可修改。` : "默认使用推荐容量，确认计算时按最终设计和用电自动匹配；可修改。",
  batteryRecommended: "推荐",
  useRecommended: "恢复推荐容量",
  pvProductPrice: "Modernite 光伏产品报价",
  conventionalPrice: "被替代的普通瓦/建材产品价",
  priceInputs: "增量投资报价（可选）",
  priceNote: "增量投资 = 光伏产品价 − 被替代的普通瓦/建材产品价 + 光伏专属成本（逆变器、并网）。共同施工成本不计入。留空则使用指示性单价。",
  previewCoverage: "家庭光伏供电比例（上次计算）",
  previewInvestment: "BIPV 增量投资",
};

const zhHant: BipvCopy = {
  ...zh,
  coverage: "家庭光電供電比例",
  coverageShort: "光電供電比例",
  chainDetail: (c, s, b) => `年用電量的 ${c}% 由光電系統滿足${b ? "（直接 + 儲能）" : "（光電直接供電）"} · 光電自消納率 ${s}%。`,
  pvUsed: "家庭使用的光電",
  pvUsedDetail: (d, b) => b ? `直接 ${d} + 儲能 ${b} kWh` : `光電直接供電 ${d} kWh`,
  selfRate: (n) => `光電自消納率 ${n}%`,
  exportRate: (n) => `售電率 ${n}%`,
  direct: "光電直接供家庭",
  directDetail: "發電當下即被家庭用掉",
  batteryToLoad: "儲能供家庭（光電來源）",
  batteryToLoadOn: "白天餘電存入電池，晚間再供家庭",
  batteryToLoadOff: "選擇「光電 + 電池」以模擬儲能",
  gridImport: "電網購電",
  scenarioRow: (l, c, s) => `${l}：供電比例 ${c}% · 自消納率 ${s}%`,
  solarOnly: "僅光電",
  withBattery: (k) => `光電 + ${k} kWh 電池`,
  battery: "電池",
  batteryValue: (k, r, a) => a ? `${k} kWh（建議容量）` : `${k} kWh（自訂 · 建議 ${r} kWh）`,
  editBattery: "修改電池容量",
  investment: "BIPV 增量投資",
  payback: "增量回收期",
  noPayback: "超過 25 年",
  formula: (pv, conv, spec) => `光電產品 ${pv} − 一般瓦/建材 ${conv} + 光電專屬 ${spec}`,
  plusBattery: (b) => `+ 電池 ${b}`,
  annualBenefit: "年度收益（節省電費 + 售電收益）",
  economicsNote: "人工、安裝、鷹架與一般屋面施工在使用一般瓦時同樣會發生，不計入光電增量投資。增量回收期 = 增量投資 ÷ 年度收益。",
  paybackLine: (inv, y) => `增量投資 ${inv} · 增量回收期 ${y}`,
  cashBreakEven: (y) => `第 ${y} 年累計現金流轉正`,
  googleTitle: "Google Solar 屋頂與傳統單晶矽參考模型 / External Roof & Solar Benchmark",
  googleLabel: "傳統單晶矽光電基準",
  googleLayout: "傳統模組排版（基準）",
  googleLayoutValue: (p, k) => `${p} 片傳統模組 · ${k} kWp`,
  googleYearly: "傳統單晶矽年發電（基準）",
  moderniteLine: "Modernite BIPV（本研究）",
  compareTitle: "同口徑比較",
  colMetric: "指標",
  googleNote: "Google 資料用於交叉驗證屋頂幾何、坡度、方位與日照，並作為傳統單晶矽光電基準；Modernite 光電瓦數量、面積、kWp 與發電量由本研究的 BIPV 引擎計算。Google 的直流值已按本研究相同的 90% 交流係數換算；兩者氣象年份可能不同。",
  ledgerCosts: (inc, pv, conv, spec, battery, est) => `${inc} = 光電產品 ${pv} − 一般瓦/建材 ${conv} + 光電專屬 ${spec}${battery ? ` · 電池 ${battery}` : ""}${est ? " · 指示性估算" : ""}`,
  ledgerCostsLabel: "BIPV 增量投資",
  batteryAuto: (r) => r ? `預設使用建議容量 ${r} kWh（上次計算），可修改。` : "預設使用建議容量，確認計算時依最終設計與用電自動匹配；可修改。",
  batteryRecommended: "建議",
  useRecommended: "恢復建議容量",
  pvProductPrice: "Modernite 光電產品報價",
  conventionalPrice: "被取代的一般瓦/建材產品價",
  priceInputs: "增量投資報價（選填）",
  priceNote: "增量投資 = 光電產品價 − 被取代的一般瓦/建材產品價 + 光電專屬成本（逆變器、併網）。共同施工成本不計入。留空則使用指示性單價。",
  previewCoverage: "家庭光電供電比例（上次計算）",
  previewInvestment: "BIPV 增量投資",
};

const fr: BipvCopy = {
  ...en,
  coverage: "Couverture solaire du foyer",
  coverageShort: "Couverture solaire",
  chainDetail: (c, s, b) => `${c} % de la demande annuelle couverte par le système solaire${b ? " (direct + stockage)" : " en direct"} · autoconsommation PV ${s} %.`,
  pvUsed: "Solaire utilisé au foyer",
  pvUsedDetail: (d, b) => b ? `Direct ${d} + batterie ${b} kWh` : `Usage direct ${d} kWh`,
  selfRate: (n) => `Autoconsommation PV ${n} %`,
  exportRate: (n) => `Taux d’injection ${n} %`,
  direct: "PV direct vers le foyer",
  directDetail: "Consommé au moment de la production",
  batteryToLoad: "Batterie vers le foyer (solaire)",
  batteryToLoadOn: "Surplus stocké puis restitué plus tard",
  batteryToLoadOff: "Choisissez solaire + batterie pour modéliser le stockage",
  gridImport: "Achat au réseau",
  scenarioRow: (l, c, s) => `${l} : couverture ${c} % · autoconsommation ${s} %`,
  solarOnly: "Solaire seul",
  withBattery: (k) => `Solaire + batterie ${k} kWh`,
  battery: "Batterie",
  batteryValue: (k, r, a) => a ? `${k} kWh (recommandée)` : `${k} kWh (personnalisée · recommandée ${r} kWh)`,
  editBattery: "Modifier la capacité",
  investment: "Investissement incrémental BIPV",
  payback: "Retour incrémental",
  years: (y) => `${y} ans`,
  noPayback: "Au-delà de 25 ans",
  formula: (pv, conv, spec) => `produits PV ${pv} − produits conventionnels ${conv} + coûts spécifiques PV ${spec}`,
  plusBattery: (b) => `+ batterie ${b}`,
  annualBenefit: "Gain annuel (économie de facture + revente)",
  economicsNote: "Main-d’œuvre, pose, échafaudage et couverture existent aussi avec des tuiles classiques : ils sont exclus de l’investissement PV. Retour = investissement incrémental ÷ gain annuel.",
  paybackLine: (inv, y) => `Investissement incrémental ${inv} · retour incrémental ${y}`,
  cashBreakEven: (y) => `Trésorerie cumulée positive en année ${y}`,
  googleTitle: "Référence externe toiture et solaire — Google Solar",
  googleLabel: "Référence PV monocristallin traditionnel",
  googleLayout: "Panneaux traditionnels (référence)",
  googleLayoutValue: (p, k) => `${p} panneaux · ${k} kWc`,
  googleYearly: "Production mono-Si traditionnelle (référence)",
  moderniteLine: "Modernite BIPV (cette étude)",
  moderniteValue: (a, k, e) => `${a} m² · ${k} kWc · ${e} kWh/an`,
  compareTitle: "Comparaison à périmètre égal",
  colMetric: "Indicateur",
  perKwp: "kWh / kWc",
  googleNote: "Les données Google servent à vérifier géométrie, pente, orientation et ensoleillement, et fournissent une référence PV monocristallin traditionnelle. Les tuiles, surfaces, kWc et productions Modernite proviennent du moteur BIPV de cette étude. La valeur CC de Google est convertie avec le même facteur CA de 90 % ; les périodes météo peuvent différer.",
  ledgerCosts: (inc, pv, conv, spec, battery, est) => `${inc} = produits PV ${pv} − conventionnels ${conv} + spécifiques PV ${spec}${battery ? ` · batterie ${battery}` : ""}${est ? " · indicatif" : ""}`,
  ledgerCostsLabel: "Investissement incrémental BIPV",
  batteryAuto: (r) => r ? `Par défaut, la capacité recommandée de ${r} kWh (dernier calcul) ; modifiable.` : "Par défaut, la capacité recommandée, ajustée au calcul selon la conception et la demande finales ; modifiable.",
  batteryRecommended: "Recommandée",
  useRecommended: "Revenir à la recommandation",
  pvProductPrice: "Devis produits PV Modernite",
  conventionalPrice: "Tuiles / bardage conventionnels remplacés",
  priceInputs: "Données d’investissement incrémental (facultatif)",
  priceNote: "Investissement incrémental = produit PV − produit conventionnel remplacé + coûts spécifiques PV (onduleur, raccordement). Les travaux communs sont exclus. Laisser vide pour des prix indicatifs.",
  previewCoverage: "Couverture solaire du foyer (dernière étude)",
  previewInvestment: "Investissement incrémental BIPV",
};

const ja: BipvCopy = {
  ...en,
  coverage: "家庭の太陽光供給率",
  coverageShort: "太陽光供給率",
  chainDetail: (c, s, b) => `年間電力需要の ${c}% を太陽光システムで供給${b ? "（直接＋蓄電）" : "（直接供給）"} · 自家消費率 ${s}%。`,
  pvUsed: "家庭で使う太陽光電力",
  pvUsedDetail: (d, b) => b ? `直接 ${d} ＋ 蓄電池 ${b} kWh` : `直接利用 ${d} kWh`,
  selfRate: (n) => `自家消費率 ${n}%`,
  exportRate: (n) => `売電率 ${n}%`,
  direct: "太陽光から直接家庭へ",
  directDetail: "発電と同時に家庭で使用",
  batteryToLoad: "蓄電池から家庭へ（太陽光由来）",
  batteryToLoadOn: "昼の余剰を蓄え、夕方以降に供給",
  batteryToLoadOff: "太陽光＋蓄電池を選ぶと蓄電を試算します",
  gridImport: "系統からの購入",
  scenarioRow: (l, c, s) => `${l}：供給率 ${c}% · 自家消費率 ${s}%`,
  solarOnly: "太陽光のみ",
  withBattery: (k) => `太陽光＋蓄電池 ${k} kWh`,
  battery: "蓄電池",
  batteryValue: (k, r, a) => a ? `${k} kWh（推奨容量）` : `${k} kWh（任意 · 推奨 ${r} kWh）`,
  editBattery: "蓄電池容量を変更",
  investment: "BIPV 増分投資",
  payback: "増分回収期間",
  years: (y) => `${y} 年`,
  noPayback: "25 年超",
  formula: (pv, conv, spec) => `太陽光製品 ${pv} − 一般瓦・建材 ${conv} ＋ 太陽光固有費用 ${spec}`,
  plusBattery: (b) => `＋ 蓄電池 ${b}`,
  annualBenefit: "年間便益（電気代削減＋売電収入）",
  economicsNote: "人件費・施工・足場・屋根工事は一般瓦でも発生するため、太陽光の増分投資には含めません。増分回収期間 = 増分投資 ÷ 年間便益。",
  paybackLine: (inv, y) => `増分投資 ${inv} · 増分回収期間 ${y}`,
  cashBreakEven: (y) => `${y} 年目に累積収支がプラス`,
  googleTitle: "Google Solar 屋根・従来型単結晶シリコン参照モデル / External Roof & Solar Benchmark",
  googleLabel: "従来型単結晶シリコン PV ベンチマーク",
  googleLayout: "従来型パネル配置（ベンチマーク）",
  googleLayoutValue: (p, k) => `従来型パネル ${p} 枚 · ${k} kWp`,
  googleYearly: "従来型単結晶の年間発電（ベンチマーク）",
  moderniteLine: "Modernite BIPV（本試算）",
  moderniteValue: (a, k, e) => `${a} m² · ${k} kWp · ${e} kWh/年`,
  compareTitle: "同一条件での比較",
  colMetric: "指標",
  googleNote: "Google のデータは屋根形状・勾配・方位・日照の照合と、従来型単結晶 PV のベンチマークに使います。Modernite の瓦枚数・面積・kWp・発電量は本試算の BIPV エンジンで計算します。Google の直流値は本試算と同じ 90% の交流係数で換算しています。気象年は異なる場合があります。",
  ledgerCosts: (inc, pv, conv, spec, battery, est) => `${inc} = 太陽光製品 ${pv} − 一般瓦・建材 ${conv} ＋ 固有費用 ${spec}${battery ? ` · 蓄電池 ${battery}` : ""}${est ? " · 目安" : ""}`,
  ledgerCostsLabel: "BIPV 増分投資",
  batteryAuto: (r) => r ? `既定は推奨容量 ${r} kWh（前回の計算）。変更できます。` : "既定は推奨容量で、計算時に最終設計と需要から選定します。変更できます。",
  batteryRecommended: "推奨",
  useRecommended: "推奨容量に戻す",
  pvProductPrice: "Modernite 太陽光製品の見積",
  conventionalPrice: "置き換える一般瓦・建材の製品価格",
  priceInputs: "増分投資の入力（任意）",
  priceNote: "増分投資 = 太陽光製品 − 置き換える一般製品 ＋ 太陽光固有費用（インバーター、系統連系）。共通工事は含みません。空欄なら目安価格を使います。",
  previewCoverage: "家庭の太陽光供給率（前回の計算）",
  previewInvestment: "BIPV 増分投資",
};

const es: BipvCopy = {
  ...en,
  coverage: "Cobertura solar del hogar",
  coverageShort: "Cobertura solar",
  chainDetail: (c, s, b) => `${c}% de la demanda anual cubierta por el sistema solar${b ? " (directo + almacenamiento)" : " de forma directa"} · autoconsumo FV ${s}%.`,
  pvUsed: "Solar usada en casa",
  pvUsedDetail: (d, b) => b ? `Directo ${d} + batería ${b} kWh` : `Uso directo ${d} kWh`,
  selfRate: (n) => `Autoconsumo FV ${n}%`,
  exportRate: (n) => `Tasa de vertido ${n}%`,
  direct: "FV directa al hogar",
  directDetail: "Se usa en el momento de generarse",
  batteryToLoad: "Batería al hogar (solar)",
  batteryToLoadOn: "Excedente almacenado y usado más tarde",
  batteryToLoadOff: "Elija solar + batería para modelar el almacenamiento",
  gridImport: "Compra a la red",
  scenarioRow: (l, c, s) => `${l}: cobertura ${c}% · autoconsumo ${s}%`,
  solarOnly: "Solo solar",
  withBattery: (k) => `Solar + batería de ${k} kWh`,
  battery: "Batería",
  batteryValue: (k, r, a) => a ? `${k} kWh (recomendada)` : `${k} kWh (personalizada · recomendada ${r} kWh)`,
  editBattery: "Cambiar capacidad",
  investment: "Inversión incremental BIPV",
  payback: "Retorno incremental",
  years: (y) => `${y} años`,
  noPayback: "Más de 25 años",
  formula: (pv, conv, spec) => `productos FV ${pv} − productos convencionales ${conv} + costes FV ${spec}`,
  plusBattery: (b) => `+ batería ${b}`,
  annualBenefit: "Beneficio anual (ahorro + ingresos por vertido)",
  economicsNote: "Mano de obra, instalación, andamios y cubierta se producen también con tejas convencionales y se excluyen de la inversión FV. Retorno = inversión incremental ÷ beneficio anual.",
  paybackLine: (inv, y) => `Inversión incremental ${inv} · retorno incremental ${y}`,
  cashBreakEven: (y) => `Caja acumulada positiva en el año ${y}`,
  googleTitle: "Referencia externa de cubierta y solar — Google Solar",
  googleLabel: "Referencia FV monocristalina tradicional",
  googleLayout: "Paneles tradicionales (referencia)",
  googleLayoutValue: (p, k) => `${p} paneles · ${k} kWp`,
  googleYearly: "Producción mono-Si tradicional (referencia)",
  moderniteLine: "Modernite BIPV (este estudio)",
  moderniteValue: (a, k, e) => `${a} m² · ${k} kWp · ${e} kWh/año`,
  compareTitle: "Comparación homogénea",
  colMetric: "Indicador",
  googleNote: "Los datos de Google contrastan geometría, pendiente, orientación y horas de sol, y aportan una referencia FV monocristalina tradicional. Tejas, superficie, kWp y producción de Modernite proceden del motor BIPV de este estudio. El valor CC de Google se convierte con el mismo factor CA del 90 %; los periodos meteorológicos pueden diferir.",
  ledgerCosts: (inc, pv, conv, spec, battery, est) => `${inc} = productos FV ${pv} − convencionales ${conv} + costes FV ${spec}${battery ? ` · batería ${battery}` : ""}${est ? " · indicativo" : ""}`,
  ledgerCostsLabel: "Inversión incremental BIPV",
  batteryAuto: (r) => r ? `Por defecto, la capacidad recomendada de ${r} kWh (último cálculo); editable.` : "Por defecto, la capacidad recomendada, ajustada al calcular según diseño y demanda finales; editable.",
  batteryRecommended: "Recomendada",
  useRecommended: "Usar la recomendada",
  pvProductPrice: "Presupuesto de productos FV Modernite",
  conventionalPrice: "Tejas / revestimiento convencional sustituido",
  priceInputs: "Datos de inversión incremental (opcional)",
  priceNote: "Inversión incremental = producto FV − producto convencional sustituido + costes FV (inversor, conexión). Se excluyen las obras comunes. Déjelo vacío para usar precios indicativos.",
  previewCoverage: "Cobertura solar del hogar (último estudio)",
  previewInvestment: "Inversión incremental BIPV",
};

const it: BipvCopy = {
  ...en,
  coverage: "Copertura solare della casa",
  coverageShort: "Copertura solare",
  chainDetail: (c, s, b) => `${c}% della domanda annua coperto dall’impianto solare${b ? " (diretto + accumulo)" : " in modo diretto"} · autoconsumo FV ${s}%.`,
  pvUsed: "Solare usato in casa",
  pvUsedDetail: (d, b) => b ? `Diretto ${d} + batteria ${b} kWh` : `Uso diretto ${d} kWh`,
  selfRate: (n) => `Autoconsumo FV ${n}%`,
  exportRate: (n) => `Quota immessa ${n}%`,
  direct: "FV diretto alla casa",
  directDetail: "Usato nel momento in cui è prodotto",
  batteryToLoad: "Batteria alla casa (solare)",
  batteryToLoadOn: "Surplus accumulato e usato più tardi",
  batteryToLoadOff: "Scegli solare + batteria per modellare l’accumulo",
  gridImport: "Prelievo dalla rete",
  scenarioRow: (l, c, s) => `${l}: copertura ${c}% · autoconsumo ${s}%`,
  solarOnly: "Solo solare",
  withBattery: (k) => `Solare + batteria da ${k} kWh`,
  battery: "Batteria",
  batteryValue: (k, r, a) => a ? `${k} kWh (consigliata)` : `${k} kWh (personalizzata · consigliata ${r} kWh)`,
  editBattery: "Modifica capacità",
  investment: "Investimento incrementale BIPV",
  payback: "Rientro incrementale",
  years: (y) => `${y} anni`,
  noPayback: "Oltre 25 anni",
  formula: (pv, conv, spec) => `prodotti FV ${pv} − prodotti convenzionali ${conv} + costi FV ${spec}`,
  plusBattery: (b) => `+ batteria ${b}`,
  annualBenefit: "Beneficio annuo (risparmio + ricavi da immissione)",
  economicsNote: "Manodopera, posa, ponteggi e lavori di copertura si sostengono anche con tegole convenzionali e sono esclusi dall’investimento FV. Rientro = investimento incrementale ÷ beneficio annuo.",
  paybackLine: (inv, y) => `Investimento incrementale ${inv} · rientro incrementale ${y}`,
  cashBreakEven: (y) => `Cassa cumulata positiva nell’anno ${y}`,
  googleTitle: "Riferimento esterno tetto e solare — Google Solar",
  googleLabel: "Riferimento FV monocristallino tradizionale",
  googleLayout: "Pannelli tradizionali (riferimento)",
  googleLayoutValue: (p, k) => `${p} pannelli · ${k} kWp`,
  googleYearly: "Produzione mono-Si tradizionale (riferimento)",
  moderniteLine: "Modernite BIPV (questo studio)",
  moderniteValue: (a, k, e) => `${a} m² · ${k} kWp · ${e} kWh/anno`,
  compareTitle: "Confronto a parità di condizioni",
  colMetric: "Indicatore",
  googleNote: "I dati Google verificano geometria, pendenza, orientamento e soleggiamento e forniscono un riferimento FV monocristallino tradizionale. Tegole, superficie, kWp e produzione Modernite derivano dal motore BIPV di questo studio. Il valore CC di Google è convertito con lo stesso fattore CA del 90 %; i periodi meteo possono differire.",
  ledgerCosts: (inc, pv, conv, spec, battery, est) => `${inc} = prodotti FV ${pv} − convenzionali ${conv} + costi FV ${spec}${battery ? ` · batteria ${battery}` : ""}${est ? " · indicativo" : ""}`,
  ledgerCostsLabel: "Investimento incrementale BIPV",
  batteryAuto: (r) => r ? `Predefinita la capacità consigliata di ${r} kWh (ultimo calcolo); modificabile.` : "Predefinita la capacità consigliata, adattata al calcolo su progetto e consumi definitivi; modificabile.",
  batteryRecommended: "Consigliata",
  useRecommended: "Usa la consigliata",
  pvProductPrice: "Preventivo prodotti FV Modernite",
  conventionalPrice: "Tegole / rivestimento convenzionale sostituito",
  priceInputs: "Dati di investimento incrementale (facoltativi)",
  priceNote: "Investimento incrementale = prodotto FV − prodotto convenzionale sostituito + costi FV (inverter, connessione). Le opere comuni sono escluse. Lascia vuoto per prezzi indicativi.",
  previewCoverage: "Copertura solare della casa (ultimo studio)",
  previewInvestment: "Investimento incrementale BIPV",
};

const COPY: Record<string, BipvCopy> = { en, zh, "zh-Hant": zhHant, fr, ja, es, it };

export const bipvCopy = (language: string): BipvCopy => COPY[language] ?? en;
