/** Copy for the unified energy balance, BIPV incremental economics and the Google Solar benchmark. */
const en = {
  coverage: "Household Solar Coverage",
  coverageShort: "Solar coverage",
  chainDetail: (coverage: number, self: number, battery: boolean) => `Solar covers ${coverage}% of the home's yearly demand${battery ? " (direct + storage)" : ""}, and ${self}% of what the roof generates is used at home.`,
  coverageNote: (used: string, load: string, coverage: number, self: number, imported: string) => `The home uses ${load} kWh a year; ${used} kWh of it comes from solar — that's ${coverage}%. ${self}% of the generation stays at home, and about ${imported} kWh still comes from the grid.`,
  pvUsed: "Solar used at home",
  pvUsedDetail: (direct: string, battery: string | null) => battery ? `${direct} kWh straight away, ${battery} kWh from the battery` : `${direct} kWh used straight away`,
  selfRate: (n: number) => `${n}% self-consumed`,
  exportRate: (n: number) => `${n}% exported`,
  direct: "Used as it's generated",
  directDetail: "Daytime power used straight away — the most valuable share",
  batteryToLoad: "Stored by day, used at night",
  batteryToLoadOn: "Surplus charges the battery and powers the home in the evening",
  batteryToLoadOff: "Pick solar + battery to see this share",
  gridImport: "Still bought from the grid",
  scenarioRow: (used: string, coverage: number, self: number) => `${used} used at home · covers ${coverage}% · ${self}% self-consumed`,
  solarOnly: "Solar only",
  withBattery: (kwh: string) => `Solar + ${kwh} kWh battery`,
  battery: "Battery",
  batteryValue: (kwh: string, rec: string, auto: boolean) => auto ? `${kwh} kWh (recommended)` : `${kwh} kWh (adjusted · we'd suggest ${rec} kWh)`,
  editBattery: "Change battery size",
  investment: "BIPV incremental investment",
  payback: "Incremental payback",
  years: (y: string) => `${y} years`,
  noPayback: "Over 25 years",
  formula: (pv: string, conv: string, spec: string) => `Solar tiles ${pv} − the ordinary tiles you'd buy anyway ${conv} + inverter & grid connection ${spec}`,
  plusBattery: (b: string) => `+ battery ${b}`,
  annualBenefit: "Yearly benefit (bill savings + export income)",
  economicsNote: "Labour, scaffolding and roofing work cost the same whichever tile you choose, so we only count the extra spent on going solar. The payback is how long that extra takes to earn back.",
  paybackLine: (inv: string, y: string) => `Extra investment ${inv} · pays back in ${y}`,
  cashBreakEven: (y: number) => `Cumulative cash turns positive in year ${y}`,
  googleTitle: "External Roof & Solar Benchmark — Google Solar",
  googleLabel: "Traditional mono-Si panel benchmark",
  googleLayout: "Google's traditional panel layout",
  googleLayoutValue: (p: number, k: string) => `${p} panels, ${k} kWp`,
  googleYearly: "Traditional panels, yearly (AC)",
  moderniteLine: "Modernite BIPV (this design)",
  moderniteValue: (area: string, kwp: string, kwh: string) => `${area} m², ${kwp} kWp, ${kwh} kWh a year`,
  compareTitle: "Side by side, on the same basis",
  colMetric: "Measure",
  perKwp: "kWh / kWp",
  perM2: "kWh / m²",
  googleNote: "We use Google's data to sense-check the roof shape, pitch, orientation and sunshine, and as a yardstick for what conventional monocrystalline panels would produce. Modernite's tile count, area, capacity and generation all come from this design's BIPV engine. To compare fairly, Google's DC output is converted with the same 90% AC factor; the two may use different weather years.",
  ledgerCosts: (inc: string, pv: string, conv: string, spec: string, battery: string | null, est: boolean) => `${inc} (solar tiles ${pv} − ordinary tiles ${conv} + inverter & connection ${spec}${battery ? ` + battery ${battery}` : ""})${est ? ", using reference prices" : ""}`,
  ledgerCostsLabel: "BIPV incremental investment",
  // Energy page
  batteryAuto: (rec: string | null) => rec ? `Filled in with the ${rec} kWh we recommended last time — change it if you like.` : "We'll size the battery to your final design and usage when you calculate. You can also set it yourself.",
  batteryRecommended: "Recommended",
  useRecommended: "Back to recommended",
  pvProductPrice: "Modernite solar tile quote",
  conventionalPrice: "Ordinary tiles / cladding you'd otherwise buy",
  priceInputs: "Have real quotes? Add them for a sharper result (optional)",
  priceNote: "Incremental investment = solar tile quote − the ordinary materials they replace + inverter and grid connection. Work you'd pay for either way isn't counted. Leave blank to use reference prices.",
  previewCoverage: "Household Solar Coverage (last calculation)",
  previewInvestment: "BIPV incremental investment",
};

export type BipvCopy = typeof en;

const zh: BipvCopy = {
  coverage: "家庭光伏供电比例",
  coverageShort: "光伏供电比例",
  chainDetail: (c, s, b) => `家里全年用电的 ${c}% 由光伏系统满足${b ? "（直接 + 储能）" : ""}，屋顶发的电有 ${s}% 留在自家用掉。`,
  coverageNote: (used, load, c, s, imp) => `家里一年用电 ${load} kWh，其中 ${used} kWh 来自光伏，占 ${c}%；发出的电有 ${s}% 自家用掉，另外还需从电网买约 ${imp} kWh。`,
  pvUsed: "自家用掉的光伏电",
  pvUsedDetail: (d, b) => b ? `边发边用 ${d} kWh，电池晚上补 ${b} kWh` : `边发边用 ${d} kWh`,
  selfRate: (n) => `自家用掉 ${n}%`,
  exportRate: (n) => `上网 ${n}%`,
  direct: "边发边用",
  directDetail: "白天发的电当场用掉，最划算的一部分",
  batteryToLoad: "白天存，晚上用",
  batteryToLoadOn: "白天多余的电先存进电池，傍晚和夜里再拿出来用",
  batteryToLoadOff: "选「光伏 + 电池」就能看到这一部分",
  gridImport: "仍需从电网买",
  scenarioRow: (used, c, s) => `自家用掉 ${used}，覆盖 ${c}% 用电，自消纳 ${s}%`,
  solarOnly: "仅光伏",
  withBattery: (k) => `光伏 + ${k} kWh 电池`,
  battery: "电池",
  batteryValue: (k, r, a) => a ? `${k} kWh（推荐）` : `${k} kWh（已手动调整，推荐 ${r} kWh）`,
  editBattery: "调整电池容量",
  investment: "BIPV 增量投资",
  payback: "增量回报期",
  years: (y) => `${y} 年`,
  noPayback: "超过 25 年",
  formula: (pv, conv, spec) => `光伏瓦 ${pv} − 原本就要买的普通瓦 ${conv} + 逆变器与并网 ${spec}`,
  plusBattery: (b) => `+ 电池 ${b}`,
  annualBenefit: "每年收益（省下的电费 + 卖电收入）",
  economicsNote: "不管选光伏瓦还是普通瓦，人工、脚手架和屋面施工都得花，所以这里只算换成光伏多花的那部分钱；增量回报期就是这笔钱靠每年收益几年能赚回来。",
  paybackLine: (inv, y) => `多投入 ${inv}，增量回报期 ${y}`,
  cashBreakEven: (y) => `第 ${y} 年累计现金流转正`,
  googleTitle: "Google Solar 屋顶与传统单晶硅参考模型 / External Roof & Solar Benchmark",
  googleLabel: "传统单晶硅光伏参考",
  googleLayout: "Google 给出的传统组件排布",
  googleLayoutValue: (p, k) => `${p} 块组件，${k} kWp`,
  googleYearly: "传统组件年发电（已折算交流）",
  moderniteLine: "Modernite BIPV（本方案）",
  moderniteValue: (a, k, e) => `${a} m²，${k} kWp，年发电 ${e} kWh`,
  compareTitle: "放在同一口径下对比",
  colMetric: "指标",
  perKwp: "kWh / kWp",
  perM2: "kWh / m²",
  googleNote: "Google 数据主要用来核对屋顶形状、坡度、朝向和日照，同时给出装传统单晶硅板大概能发多少电，作为参照。Modernite 光伏瓦的数量、面积、装机和发电量都由本方案的 BIPV 引擎计算。为了对比公平，Google 的直流发电量按同样的 90% 折算成交流；两边采用的气象年份可能不同。",
  ledgerCosts: (inc, pv, conv, spec, battery, est) => `${inc}（光伏瓦 ${pv} − 普通瓦 ${conv} + 逆变器与并网 ${spec}${battery ? ` + 电池 ${battery}` : ""}）${est ? "，按参考单价估算" : ""}`,
  ledgerCostsLabel: "BIPV 增量投资",
  batteryAuto: (r) => r ? `已按上次计算填入推荐容量 ${r} kWh，想调整直接改就行。` : "先用推荐容量，点计算时会按最终设计和用电量自动配好；也可以自己填。",
  batteryRecommended: "推荐",
  useRecommended: "改回推荐容量",
  pvProductPrice: "Modernite 光伏瓦报价",
  conventionalPrice: "原本要用的普通瓦 / 外墙材料价格",
  priceInputs: "有实际报价？填进来算得更准（可选）",
  priceNote: "增量投资 = 光伏瓦报价 − 被替换掉的普通材料 + 逆变器和并网这类光伏才需要的费用。两种方案都要花的施工费不算在内。不填就按参考单价估算。",
  previewCoverage: "家庭光伏供电比例（上次计算）",
  previewInvestment: "BIPV 增量投资",
};

const zhHant: BipvCopy = {
  ...zh,
  coverage: "家庭光電供電比例",
  coverageShort: "光電供電比例",
  chainDetail: (c, s, b) => `家裡全年用電的 ${c}% 由光電系統滿足${b ? "（直接 + 儲能）" : ""}，屋頂發的電有 ${s}% 留在自家使用。`,
  coverageNote: (used, load, c, s, imp) => `家裡一年用電 ${load} kWh，其中 ${used} kWh 來自光電，佔 ${c}%；發出的電有 ${s}% 自家使用，另外仍需向電網購買約 ${imp} kWh。`,
  pvUsed: "自家使用的光電",
  pvUsedDetail: (d, b) => b ? `邊發邊用 ${d} kWh，電池晚上補 ${b} kWh` : `邊發邊用 ${d} kWh`,
  selfRate: (n) => `自家使用 ${n}%`,
  exportRate: (n) => `售電 ${n}%`,
  direct: "邊發邊用",
  directDetail: "白天發的電當下用掉，最划算的一部分",
  batteryToLoad: "白天存，晚上用",
  batteryToLoadOn: "白天多餘的電先存進電池，傍晚和夜裡再拿出來用",
  batteryToLoadOff: "選「光電 + 電池」就能看到這一部分",
  gridImport: "仍需向電網購買",
  scenarioRow: (used, c, s) => `自家使用 ${used}，涵蓋 ${c}% 用電，自消納 ${s}%`,
  solarOnly: "僅光電",
  withBattery: (k) => `光電 + ${k} kWh 電池`,
  battery: "電池",
  batteryValue: (k, r, a) => a ? `${k} kWh（建議）` : `${k} kWh（已手動調整，建議 ${r} kWh）`,
  editBattery: "調整電池容量",
  investment: "BIPV 增量投資",
  payback: "增量回收期",
  noPayback: "超過 25 年",
  formula: (pv, conv, spec) => `光電瓦 ${pv} − 原本就要買的一般瓦 ${conv} + 逆變器與併網 ${spec}`,
  plusBattery: (b) => `+ 電池 ${b}`,
  annualBenefit: "每年收益（省下的電費 + 售電收入）",
  economicsNote: "不論選光電瓦還是一般瓦，人工、鷹架和屋面施工都要花，所以這裡只算改用光電多花的那部分；增量回收期就是這筆錢靠每年收益幾年能賺回來。",
  paybackLine: (inv, y) => `多投入 ${inv}，增量回收期 ${y}`,
  cashBreakEven: (y) => `第 ${y} 年累計現金流轉正`,
  googleTitle: "Google Solar 屋頂與傳統單晶矽參考模型 / External Roof & Solar Benchmark",
  googleLabel: "傳統單晶矽光電參考",
  googleLayout: "Google 給出的傳統模組排列",
  googleLayoutValue: (p, k) => `${p} 片模組，${k} kWp`,
  googleYearly: "傳統模組年發電（已折算交流）",
  moderniteLine: "Modernite BIPV（本方案）",
  moderniteValue: (a, k, e) => `${a} m²，${k} kWp，年發電 ${e} kWh`,
  compareTitle: "放在同一口徑下比較",
  colMetric: "指標",
  googleNote: "Google 資料主要用來核對屋頂形狀、坡度、方位和日照，同時給出安裝傳統單晶矽板大約能發多少電，作為參照。Modernite 光電瓦的數量、面積、裝置容量和發電量都由本方案的 BIPV 引擎計算。為了比較公平，Google 的直流發電量按同樣的 90% 折算成交流；兩邊採用的氣象年份可能不同。",
  ledgerCosts: (inc, pv, conv, spec, battery, est) => `${inc}（光電瓦 ${pv} − 一般瓦 ${conv} + 逆變器與併網 ${spec}${battery ? ` + 電池 ${battery}` : ""}）${est ? "，按參考單價估算" : ""}`,
  ledgerCostsLabel: "BIPV 增量投資",
  batteryAuto: (r) => r ? `已按上次計算填入建議容量 ${r} kWh，想調整直接改即可。` : "先用建議容量，按計算時會依最終設計和用電量自動配好；也可以自行填寫。",
  batteryRecommended: "建議",
  useRecommended: "改回建議容量",
  pvProductPrice: "Modernite 光電瓦報價",
  conventionalPrice: "原本要用的一般瓦 / 外牆材料價格",
  priceInputs: "有實際報價？填進來算得更準（選填）",
  priceNote: "增量投資 = 光電瓦報價 − 被替換掉的一般材料 + 逆變器和併網這類光電才需要的費用。兩種方案都要花的施工費不計入。不填就按參考單價估算。",
  previewCoverage: "家庭光電供電比例（上次計算）",
  previewInvestment: "BIPV 增量投資",
};

const fr: BipvCopy = {
  ...en,
  coverage: "Couverture solaire du foyer",
  coverageShort: "Couverture solaire",
  chainDetail: (c, s, b) => `Le solaire couvre ${c} % des besoins annuels du foyer${b ? " (direct + stockage)" : ""}, et ${s} % de la production est consommée sur place.`,
  coverageNote: (used, load, c, s, imp) => `Le foyer consomme ${load} kWh par an, dont ${used} kWh d’origine solaire, soit ${c} %. ${s} % de la production reste à la maison ; environ ${imp} kWh viennent encore du réseau.`,
  pvUsed: "Solaire consommé à la maison",
  pvUsedDetail: (d, b) => b ? `${d} kWh au fil de la production, ${b} kWh restitués par la batterie` : `${d} kWh au fil de la production`,
  selfRate: (n) => `${n} % autoconsommé`,
  exportRate: (n) => `${n} % injecté`,
  direct: "Consommé à la production",
  directDetail: "L’électricité de la journée utilisée tout de suite — la part la plus rentable",
  batteryToLoad: "Stocké le jour, utilisé le soir",
  batteryToLoadOn: "Le surplus charge la batterie et alimente la maison le soir",
  batteryToLoadOff: "Choisissez solaire + batterie pour voir cette part",
  gridImport: "Encore acheté au réseau",
  scenarioRow: (used, c, s) => `${used} consommés sur place · couvre ${c} % · ${s} % autoconsommé`,
  solarOnly: "Solaire seul",
  withBattery: (k) => `Solaire + batterie ${k} kWh`,
  battery: "Batterie",
  batteryValue: (k, r, a) => a ? `${k} kWh (recommandée)` : `${k} kWh (ajustée · nous conseillons ${r} kWh)`,
  editBattery: "Modifier la batterie",
  investment: "Investissement incrémental BIPV",
  payback: "Retour incrémental",
  years: (y) => `${y} ans`,
  noPayback: "Plus de 25 ans",
  formula: (pv, conv, spec) => `tuiles solaires ${pv} − tuiles classiques achetées de toute façon ${conv} + onduleur et raccordement ${spec}`,
  plusBattery: (b) => `+ batterie ${b}`,
  annualBenefit: "Gain annuel (économies + revente)",
  economicsNote: "Main-d’œuvre, échafaudage et couverture coûtent la même chose quelle que soit la tuile : nous ne comptons que le surcoût du solaire. Le retour indique en combien d’années ce surcoût est remboursé.",
  paybackLine: (inv, y) => `Surcoût ${inv} · remboursé en ${y}`,
  cashBreakEven: (y) => `Trésorerie cumulée positive dès l’année ${y}`,
  googleTitle: "Référence externe toiture et solaire — Google Solar",
  googleLabel: "Référence panneaux monocristallins classiques",
  googleLayout: "Calepinage classique proposé par Google",
  googleLayoutValue: (p, k) => `${p} panneaux, ${k} kWc`,
  googleYearly: "Panneaux classiques, production annuelle (CA)",
  moderniteLine: "Modernite BIPV (ce projet)",
  moderniteValue: (a, k, e) => `${a} m², ${k} kWc, ${e} kWh par an`,
  compareTitle: "Côte à côte, sur la même base",
  colMetric: "Indicateur",
  perKwp: "kWh / kWc",
  googleNote: "Les données Google servent à vérifier la forme du toit, la pente, l’orientation et l’ensoleillement, et donnent un repère de ce que produiraient des panneaux monocristallins classiques. Tuiles, surface, puissance et production Modernite viennent du moteur BIPV de ce projet. Pour comparer équitablement, la valeur CC de Google est convertie avec le même facteur CA de 90 % ; les années météo peuvent différer.",
  ledgerCosts: (inc, pv, conv, spec, battery, est) => `${inc} (tuiles solaires ${pv} − tuiles classiques ${conv} + onduleur et raccordement ${spec}${battery ? ` + batterie ${battery}` : ""})${est ? ", prix de référence" : ""}`,
  ledgerCostsLabel: "Investissement incrémental BIPV",
  batteryAuto: (r) => r ? `Pré-rempli avec les ${r} kWh recommandés au dernier calcul — modifiez si besoin.` : "Nous dimensionnerons la batterie selon votre projet et votre consommation au moment du calcul. Vous pouvez aussi la fixer vous-même.",
  batteryRecommended: "Recommandée",
  useRecommended: "Revenir à la recommandation",
  pvProductPrice: "Devis tuiles solaires Modernite",
  conventionalPrice: "Tuiles / bardage classiques que vous auriez achetés",
  priceInputs: "Vous avez des devis ? Ajoutez-les pour affiner (facultatif)",
  priceNote: "Investissement incrémental = devis tuiles solaires − matériaux classiques remplacés + onduleur et raccordement. Les travaux payés dans tous les cas ne sont pas comptés. Laissez vide pour utiliser des prix de référence.",
  previewCoverage: "Couverture solaire du foyer (dernier calcul)",
  previewInvestment: "Investissement incrémental BIPV",
};

const ja: BipvCopy = {
  ...en,
  coverage: "家庭の太陽光供給率",
  coverageShort: "太陽光供給率",
  chainDetail: (c, s, b) => `年間の電力需要の ${c}% を太陽光でまかない${b ? "（直接＋蓄電）" : ""}、発電量の ${s}% を自宅で使います。`,
  coverageNote: (used, load, c, s, imp) => `年間使用量 ${load} kWh のうち ${used} kWh が太陽光で、${c}% にあたります。発電の ${s}% を自宅で使い、残りは売電。系統からはまだ約 ${imp} kWh を購入します。`,
  pvUsed: "自宅で使う太陽光",
  pvUsedDetail: (d, b) => b ? `発電しながら ${d} kWh、夜に蓄電池から ${b} kWh` : `発電しながら ${d} kWh`,
  selfRate: (n) => `自家消費 ${n}%`,
  exportRate: (n) => `売電 ${n}%`,
  direct: "発電しながら使う",
  directDetail: "昼の電気をその場で使う、いちばんお得な部分",
  batteryToLoad: "昼に貯めて夜に使う",
  batteryToLoadOn: "昼の余剰を蓄電池に貯め、夕方以降に使います",
  batteryToLoadOff: "太陽光＋蓄電池を選ぶとこの部分が表示されます",
  gridImport: "まだ系統から購入",
  scenarioRow: (used, c, s) => `自宅で ${used} 使用 · 供給率 ${c}% · 自家消費 ${s}%`,
  solarOnly: "太陽光のみ",
  withBattery: (k) => `太陽光＋蓄電池 ${k} kWh`,
  battery: "蓄電池",
  batteryValue: (k, r, a) => a ? `${k} kWh（推奨）` : `${k} kWh（変更済み · 推奨は ${r} kWh）`,
  editBattery: "蓄電池容量を変更",
  investment: "BIPV 増分投資",
  payback: "増分回収期間",
  years: (y) => `${y} 年`,
  noPayback: "25 年超",
  formula: (pv, conv, spec) => `太陽光瓦 ${pv} − どのみち必要な一般瓦 ${conv} ＋ インバーター・系統連系 ${spec}`,
  plusBattery: (b) => `＋ 蓄電池 ${b}`,
  annualBenefit: "年間メリット（電気代削減＋売電収入）",
  economicsNote: "人件費・足場・屋根工事はどの瓦を選んでもかかるため、太陽光にした分の追加費用だけを数えています。増分回収期間は、その追加費用を何年で取り戻せるかを示します。",
  paybackLine: (inv, y) => `追加費用 ${inv} · ${y}で回収`,
  cashBreakEven: (y) => `${y} 年目に累積収支がプラス`,
  googleTitle: "Google Solar 屋根・従来型単結晶シリコン参照モデル / External Roof & Solar Benchmark",
  googleLabel: "従来型単結晶パネルの参照値",
  googleLayout: "Google による従来型パネル配置",
  googleLayoutValue: (p, k) => `${p} 枚、${k} kWp`,
  googleYearly: "従来型パネルの年間発電（交流換算）",
  moderniteLine: "Modernite BIPV（本プラン）",
  moderniteValue: (a, k, e) => `${a} m²、${k} kWp、年間 ${e} kWh`,
  compareTitle: "同じ条件で並べて比較",
  colMetric: "指標",
  googleNote: "Google のデータは屋根形状・勾配・方位・日照の確認と、従来型単結晶パネルならどれだけ発電するかの目安に使っています。Modernite の瓦枚数・面積・容量・発電量は本プランの BIPV エンジンで計算しています。公平に比べるため、Google の直流値は同じ 90% の交流係数で換算しています。気象年は異なる場合があります。",
  ledgerCosts: (inc, pv, conv, spec, battery, est) => `${inc}（太陽光瓦 ${pv} − 一般瓦 ${conv} ＋ インバーター・連系 ${spec}${battery ? ` ＋ 蓄電池 ${battery}` : ""}）${est ? "、参考単価で試算" : ""}`,
  ledgerCostsLabel: "BIPV 増分投資",
  batteryAuto: (r) => r ? `前回の計算で推奨した ${r} kWh を入れています。必要なら変更してください。` : "計算時に最終設計と使用量に合わせて容量を選びます。ご自身で入力することもできます。",
  batteryRecommended: "推奨",
  useRecommended: "推奨容量に戻す",
  pvProductPrice: "Modernite 太陽光瓦の見積",
  conventionalPrice: "本来使う一般瓦・外装材の価格",
  priceInputs: "実際の見積があれば入力するとより正確に（任意）",
  priceNote: "増分投資 = 太陽光瓦の見積 − 置き換わる一般材料 ＋ インバーター・系統連系の費用。どちらでもかかる工事費は含みません。空欄なら参考単価で試算します。",
  previewCoverage: "家庭の太陽光供給率（前回の計算）",
  previewInvestment: "BIPV 増分投資",
};

const es: BipvCopy = {
  ...en,
  coverage: "Cobertura solar del hogar",
  coverageShort: "Cobertura solar",
  chainDetail: (c, s, b) => `La solar cubre el ${c}% de la demanda anual de la casa${b ? " (directo + almacenamiento)" : ""}, y el ${s}% de lo que genera el tejado se usa en casa.`,
  coverageNote: (used, load, c, s, imp) => `La casa consume ${load} kWh al año; ${used} kWh salen de la solar, es decir, el ${c}%. El ${s}% de la producción se queda en casa y todavía se compran unos ${imp} kWh a la red.`,
  pvUsed: "Solar usada en casa",
  pvUsedDetail: (d, b) => b ? `${d} kWh al momento, ${b} kWh después desde la batería` : `${d} kWh al momento`,
  selfRate: (n) => `${n}% autoconsumido`,
  exportRate: (n) => `${n}% vertido`,
  direct: "Usada al momento",
  directDetail: "La energía del día aprovechada al instante: la parte más rentable",
  batteryToLoad: "Se guarda de día, se usa de noche",
  batteryToLoadOn: "El excedente carga la batería y alimenta la casa por la tarde",
  batteryToLoadOff: "Elige solar + batería para ver esta parte",
  gridImport: "Aún comprado a la red",
  scenarioRow: (used, c, s) => `${used} usados en casa · cubre el ${c}% · ${s}% autoconsumido`,
  solarOnly: "Solo solar",
  withBattery: (k) => `Solar + batería de ${k} kWh`,
  battery: "Batería",
  batteryValue: (k, r, a) => a ? `${k} kWh (recomendada)` : `${k} kWh (ajustada · sugerimos ${r} kWh)`,
  editBattery: "Cambiar la batería",
  investment: "Inversión incremental BIPV",
  payback: "Retorno incremental",
  years: (y) => `${y} años`,
  noPayback: "Más de 25 años",
  formula: (pv, conv, spec) => `tejas solares ${pv} − tejas normales que comprarías igualmente ${conv} + inversor y conexión ${spec}`,
  plusBattery: (b) => `+ batería ${b}`,
  annualBenefit: "Beneficio anual (ahorro + ingresos por vertido)",
  economicsNote: "Mano de obra, andamios y cubierta cuestan lo mismo con cualquier teja, así que solo contamos lo que cuesta de más pasarse a la solar. El retorno indica en cuántos años se recupera esa diferencia.",
  paybackLine: (inv, y) => `Inversión extra ${inv} · se recupera en ${y}`,
  cashBreakEven: (y) => `La caja acumulada pasa a positivo en el año ${y}`,
  googleTitle: "Referencia externa de cubierta y solar — Google Solar",
  googleLabel: "Referencia de paneles monocristalinos convencionales",
  googleLayout: "Distribución convencional propuesta por Google",
  googleLayoutValue: (p, k) => `${p} paneles, ${k} kWp`,
  googleYearly: "Paneles convencionales, producción anual (CA)",
  moderniteLine: "Modernite BIPV (este diseño)",
  moderniteValue: (a, k, e) => `${a} m², ${k} kWp, ${e} kWh al año`,
  compareTitle: "Lado a lado, con el mismo criterio",
  colMetric: "Indicador",
  googleNote: "Usamos los datos de Google para comprobar la forma del tejado, la pendiente, la orientación y el sol, y como referencia de lo que producirían paneles monocristalinos convencionales. Tejas, superficie, potencia y producción de Modernite salen del motor BIPV de este diseño. Para comparar con justicia, el valor CC de Google se convierte con el mismo factor CA del 90 %; los años meteorológicos pueden diferir.",
  ledgerCosts: (inc, pv, conv, spec, battery, est) => `${inc} (tejas solares ${pv} − tejas normales ${conv} + inversor y conexión ${spec}${battery ? ` + batería ${battery}` : ""})${est ? ", con precios de referencia" : ""}`,
  ledgerCostsLabel: "Inversión incremental BIPV",
  batteryAuto: (r) => r ? `Rellenado con los ${r} kWh que recomendamos la última vez; cámbialo si quieres.` : "Al calcular, ajustaremos la batería a tu diseño y consumo finales. También puedes fijarla tú.",
  batteryRecommended: "Recomendada",
  useRecommended: "Volver a la recomendada",
  pvProductPrice: "Presupuesto de tejas solares Modernite",
  conventionalPrice: "Tejas / revestimiento normal que comprarías",
  priceInputs: "¿Tienes presupuestos reales? Añádelos para afinar (opcional)",
  priceNote: "Inversión incremental = presupuesto de tejas solares − materiales normales que sustituyen + inversor y conexión a red. Lo que pagarías en cualquier caso no cuenta. Déjalo vacío para usar precios de referencia.",
  previewCoverage: "Cobertura solar del hogar (último cálculo)",
  previewInvestment: "Inversión incremental BIPV",
};

const it: BipvCopy = {
  ...en,
  coverage: "Copertura solare della casa",
  coverageShort: "Copertura solare",
  chainDetail: (c, s, b) => `Il solare copre il ${c}% del fabbisogno annuo della casa${b ? " (diretto + accumulo)" : ""}, e il ${s}% di ciò che produce il tetto viene usato in casa.`,
  coverageNote: (used, load, c, s, imp) => `La casa consuma ${load} kWh l’anno; ${used} kWh arrivano dal solare, cioè il ${c}%. Il ${s}% della produzione resta in casa e circa ${imp} kWh si prelevano ancora dalla rete.`,
  pvUsed: "Solare usato in casa",
  pvUsedDetail: (d, b) => b ? `${d} kWh subito, ${b} kWh più tardi dalla batteria` : `${d} kWh subito`,
  selfRate: (n) => `${n}% autoconsumato`,
  exportRate: (n) => `${n}% immesso`,
  direct: "Usato subito",
  directDetail: "L’energia del giorno usata all’istante: la quota più conveniente",
  batteryToLoad: "Accumulato di giorno, usato la sera",
  batteryToLoadOn: "Il surplus carica la batteria e alimenta la casa la sera",
  batteryToLoadOff: "Scegli solare + batteria per vedere questa quota",
  gridImport: "Ancora prelevato dalla rete",
  scenarioRow: (used, c, s) => `${used} usati in casa · copre il ${c}% · ${s}% autoconsumato`,
  solarOnly: "Solo solare",
  withBattery: (k) => `Solare + batteria da ${k} kWh`,
  battery: "Batteria",
  batteryValue: (k, r, a) => a ? `${k} kWh (consigliata)` : `${k} kWh (modificata · consigliamo ${r} kWh)`,
  editBattery: "Modifica la batteria",
  investment: "Investimento incrementale BIPV",
  payback: "Rientro incrementale",
  years: (y) => `${y} anni`,
  noPayback: "Oltre 25 anni",
  formula: (pv, conv, spec) => `tegole solari ${pv} − tegole normali che compreresti comunque ${conv} + inverter e allaccio ${spec}`,
  plusBattery: (b) => `+ batteria ${b}`,
  annualBenefit: "Beneficio annuo (risparmio + ricavi da immissione)",
  economicsNote: "Manodopera, ponteggi e lavori di copertura costano uguale con qualsiasi tegola, quindi contiamo solo la spesa in più per il solare. Il rientro indica in quanti anni la si recupera.",
  paybackLine: (inv, y) => `Spesa in più ${inv} · rientro in ${y}`,
  cashBreakEven: (y) => `Cassa cumulata in positivo dall’anno ${y}`,
  googleTitle: "Riferimento esterno tetto e solare — Google Solar",
  googleLabel: "Riferimento pannelli monocristallini tradizionali",
  googleLayout: "Disposizione tradizionale proposta da Google",
  googleLayoutValue: (p, k) => `${p} pannelli, ${k} kWp`,
  googleYearly: "Pannelli tradizionali, produzione annua (CA)",
  moderniteLine: "Modernite BIPV (questo progetto)",
  moderniteValue: (a, k, e) => `${a} m², ${k} kWp, ${e} kWh l’anno`,
  compareTitle: "Fianco a fianco, con lo stesso criterio",
  colMetric: "Indicatore",
  googleNote: "Usiamo i dati Google per verificare forma del tetto, pendenza, orientamento e soleggiamento, e come riferimento per ciò che produrrebbero pannelli monocristallini tradizionali. Tegole, superficie, potenza e produzione Modernite derivano dal motore BIPV di questo progetto. Per un confronto equo, il valore CC di Google è convertito con lo stesso fattore CA del 90 %; gli anni meteo possono differire.",
  ledgerCosts: (inc, pv, conv, spec, battery, est) => `${inc} (tegole solari ${pv} − tegole normali ${conv} + inverter e allaccio ${spec}${battery ? ` + batteria ${battery}` : ""})${est ? ", con prezzi di riferimento" : ""}`,
  ledgerCostsLabel: "Investimento incrementale BIPV",
  batteryAuto: (r) => r ? `Compilato con i ${r} kWh consigliati l’ultima volta: modificalo se vuoi.` : "Al calcolo dimensioneremo la batteria su progetto e consumi definitivi. Puoi anche impostarla tu.",
  batteryRecommended: "Consigliata",
  useRecommended: "Torna alla consigliata",
  pvProductPrice: "Preventivo tegole solari Modernite",
  conventionalPrice: "Tegole / rivestimento normale che compreresti",
  priceInputs: "Hai preventivi reali? Inseriscili per un risultato più preciso (facoltativo)",
  priceNote: "Investimento incrementale = preventivo tegole solari − materiali normali sostituiti + inverter e allaccio alla rete. Ciò che pagheresti comunque non è contato. Lascia vuoto per usare prezzi di riferimento.",
  previewCoverage: "Copertura solare della casa (ultimo calcolo)",
  previewInvestment: "Investimento incrementale BIPV",
};

const COPY: Record<string, BipvCopy> = { en, zh, "zh-Hant": zhHant, fr, ja, es, it };

export const bipvCopy = (language: string): BipvCopy => COPY[language] ?? en;
