import fs from "node:fs";
import path from "node:path";

const root = "/home/ubuntu/modernite-bipv-platform/i18n";
const additions = {
  en: {
    "nav.structures": "Add structures", "nav.products": "Choose solar products",
    "map.pegman_hint": "Drag the official Google Pegman onto a blue road line to open Street View.",
    "roof.locate_property": "Locate property",
    "building.form_title": "Choose the closest building form", "building.form_lead": "Choose a starting form, then adjust the dimensions and solar tilt. The 3D study updates as you work.", "building.live_model_help": "Orbit the model to inspect the form, roof pitch and BIPV surfaces.", "building.next_structures": "Next: add structures",
    "structures.step": "Step 4 of 6", "structures.title": "Add additional structures", "structures.lead": "Choose any structures present at the site. Each one keeps its own editable dimensions.", "structures.choose_many": "Choose one, several, or none", "structures.none": "No additional structures", "structures.none_help": "Continue with the main building only.", "structures.parameters": "Selected structure", "structures.parameters_help": "These settings apply only to the selected structure.", "structures.no_selection": "Nothing selected", "structures.select_to_edit": "Choose a conservatory, carport or entrance canopy to edit its dimensions.", "structures.eaves_height": "Eaves height (m)", "structures.solar_coverage": "Solar coverage", "structures.remove": "Remove", "structures.next_products": "Next: choose solar products", "structures.conservatory": "Solar conservatory", "structures.conservatory_detail": "Glazed extension with a photovoltaic roof.", "structures.carport": "Solar carport", "structures.carport_detail": "Clear-span vehicle shelter with a solar canopy.", "structures.canopy": "Solar entrance canopy", "structures.canopy_detail": "Compact solar shelter over an entrance or terrace.",
    "library.roof": "Roof", "library.roof_lead": "Solar tiles and slates for the measured roof surfaces.", "library.facade": "Facade", "library.facade_lead": "Opaque and light-transmitting solar façade modules.", "library.window": "Windows & glass", "library.window_lead": "Photovoltaic glazing for windows and rooflights.", "library.railing": "Railing", "library.railing_lead": "Solar glass balustrades for balconies and terraces.", "library.structure": "Additional structures", "library.structure_lead": "Solar glass and canopy products for selected structures.",
    "products.library_title": "Choose solar products", "products.library_lead": "Use the library by surface type. Your selections remain independent, so roof, façade, glazing, railings and structures never overwrite one another.", "products.library_label": "Surface library", "products.selected_count": "selected", "products.choose_material": "Choose a material", "products.live_model": "Live design study", "products.live_model_help": "Click a surface in the 3D study to open its matching library.", "products.next_review": "Next: review and simulate"
  },
  zh: {
    "nav.structures": "附加结构", "nav.products": "选择光伏产品",
    "map.pegman_hint": "将 Google 官方小人拖到蓝色道路线上，即可进入街景。",
    "roof.locate_property": "定位项目地址",
    "building.form_title": "选择最接近的建筑形式", "building.form_lead": "先选择建筑形式，再调整尺寸与光伏倾角。3D 模型会同步更新。", "building.live_model_help": "拖动模型以查看建筑形式、屋顶坡度和光伏表面。", "building.next_structures": "下一步：附加结构",
    "structures.step": "第 4 步，共 6 步", "structures.title": "添加附加结构", "structures.lead": "选择项目中存在的附加结构。每一项都拥有独立可编辑的尺寸。", "structures.choose_many": "可选择一个、多个或不选择", "structures.none": "无附加结构", "structures.none_help": "仅使用主体建筑继续。", "structures.parameters": "已选结构", "structures.parameters_help": "这些设置仅适用于当前选中的结构。", "structures.no_selection": "尚未选择结构", "structures.select_to_edit": "选择阳光房、车棚或入口雨棚，然后编辑其尺寸。", "structures.eaves_height": "檐口高度（m）", "structures.solar_coverage": "光伏覆盖率", "structures.remove": "移除", "structures.next_products": "下一步：选择光伏产品", "structures.conservatory": "光伏阳光房", "structures.conservatory_detail": "带光伏屋顶的玻璃扩建空间。", "structures.carport": "光伏车棚", "structures.carport_detail": "采用光伏雨棚的大跨度车辆遮蔽空间。", "structures.canopy": "光伏入口雨棚", "structures.canopy_detail": "用于入口或露台的紧凑型光伏遮阳结构。",
    "library.roof": "屋顶", "library.roof_lead": "用于已测量屋顶表面的光伏瓦与光伏板。", "library.facade": "立面", "library.facade_lead": "不透光及透光型光伏立面模块。", "library.window": "窗户与玻璃", "library.window_lead": "用于窗户和天窗的光伏玻璃。", "library.railing": "栏杆", "library.railing_lead": "适用于阳台和露台的光伏玻璃栏杆。", "library.structure": "附加结构", "library.structure_lead": "为已选附加结构配置的光伏玻璃和雨棚产品。",
    "products.library_title": "选择光伏产品", "products.library_lead": "按表面类型使用产品库。屋顶、立面、玻璃、栏杆和附加结构的选择相互独立，不会互相覆盖。", "products.library_label": "表面产品库", "products.selected_count": "已选择", "products.choose_material": "选择材料", "products.live_model": "实时设计模型", "products.live_model_help": "在 3D 模型中点击表面，即可打开对应产品库。", "products.next_review": "下一步：复核并模拟"
  },
  ja: {
    "nav.structures": "付加構造", "nav.products": "太陽光製品を選択",
    "map.pegman_hint": "Google 公式のペグマンを青い道路線へドラッグするとストリートビューを開けます。",
    "roof.locate_property": "物件を検索",
    "building.form_title": "近い建物形式を選択", "building.form_lead": "まず建物形式を選び、寸法と太陽光の傾斜を調整します。3Dモデルは操作に応じて更新されます。", "building.live_model_help": "モデルを回転して、形状・屋根勾配・BIPV面を確認できます。", "building.next_structures": "次へ：付加構造",
    "structures.step": "ステップ 4 / 6", "structures.title": "付加構造を追加", "structures.lead": "敷地にある付加構造を選択してください。各構造には個別に編集できる寸法があります。", "structures.choose_many": "1つ、複数、またはなしを選択", "structures.none": "付加構造なし", "structures.none_help": "主建物のみで続行します。", "structures.parameters": "選択中の構造", "structures.parameters_help": "この設定は選択中の構造にのみ適用されます。", "structures.no_selection": "未選択", "structures.select_to_edit": "サンルーム、カーポート、または玄関キャノピーを選び、寸法を編集します。", "structures.eaves_height": "軒高（m）", "structures.solar_coverage": "太陽光カバー率", "structures.remove": "削除", "structures.next_products": "次へ：太陽光製品を選択", "structures.conservatory": "ソーラーサンルーム", "structures.conservatory_detail": "太陽光屋根を備えたガラス張りの増築。", "structures.carport": "ソーラーカーポート", "structures.carport_detail": "太陽光キャノピーを備えた車両用シェルター。", "structures.canopy": "ソーラー玄関キャノピー", "structures.canopy_detail": "玄関やテラス向けのコンパクトな太陽光庇。",
    "library.roof": "屋根", "library.roof_lead": "計測した屋根面のソーラータイルとスレート。", "library.facade": "ファサード", "library.facade_lead": "不透明および透光型の太陽光ファサードモジュール。", "library.window": "窓・ガラス", "library.window_lead": "窓とトップライト用の太陽光ガラス。", "library.railing": "手すり", "library.railing_lead": "バルコニーとテラス用の太陽光ガラス手すり。", "library.structure": "付加構造", "library.structure_lead": "選択した付加構造用の太陽光ガラス・キャノピー製品。",
    "products.library_title": "太陽光製品を選択", "products.library_lead": "表面タイプごとにライブラリを使用します。屋根、ファサード、ガラス、手すり、付加構造の選択は独立しており、互いに上書きしません。", "products.library_label": "表面ライブラリ", "products.selected_count": "選択済み", "products.choose_material": "材料を選択", "products.live_model": "ライブデザインモデル", "products.live_model_help": "3Dモデルの面をクリックして、対応するライブラリを開きます。", "products.next_review": "次へ：レビューとシミュレーション"
  },
  fr: {
    "nav.structures": "Ajouter des structures", "nav.products": "Choisir les produits solaires",
    "map.pegman_hint": "Faites glisser le Pegman officiel de Google sur une ligne routière bleue pour ouvrir Street View.",
    "roof.locate_property": "Localiser le bien",
    "building.form_title": "Choisir la forme de bâtiment la plus proche", "building.form_lead": "Choisissez une forme de départ, puis ajustez les dimensions et l'inclinaison solaire. L'étude 3D se met à jour pendant la configuration.", "building.live_model_help": "Faites pivoter le modèle pour examiner la forme, la pente du toit et les surfaces BIPV.", "building.next_structures": "Suivant : ajouter des structures",
    "structures.step": "Étape 4 sur 6", "structures.title": "Ajouter des structures supplémentaires", "structures.lead": "Choisissez les structures présentes sur le site. Chaque structure conserve ses propres dimensions modifiables.", "structures.choose_many": "Choisissez une, plusieurs ou aucune structure", "structures.none": "Aucune structure supplémentaire", "structures.none_help": "Continuer avec le bâtiment principal uniquement.", "structures.parameters": "Structure sélectionnée", "structures.parameters_help": "Ces réglages s'appliquent uniquement à la structure sélectionnée.", "structures.no_selection": "Aucune sélection", "structures.select_to_edit": "Choisissez une véranda, un carport ou un auvent d'entrée pour modifier ses dimensions.", "structures.eaves_height": "Hauteur d'égout (m)", "structures.solar_coverage": "Couverture solaire", "structures.remove": "Retirer", "structures.next_products": "Suivant : choisir les produits solaires", "structures.conservatory": "Véranda solaire", "structures.conservatory_detail": "Extension vitrée avec un toit photovoltaïque.", "structures.carport": "Carport solaire", "structures.carport_detail": "Abri pour véhicule à couverture photovoltaïque.", "structures.canopy": "Auvent d'entrée solaire", "structures.canopy_detail": "Abri solaire compact pour une entrée ou une terrasse.",
    "library.roof": "Toiture", "library.roof_lead": "Tuiles et ardoises solaires pour les surfaces de toit mesurées.", "library.facade": "Façade", "library.facade_lead": "Modules solaires de façade opaques et translucides.", "library.window": "Fenêtres et vitrage", "library.window_lead": "Vitrage photovoltaïque pour fenêtres et lanterneaux.", "library.railing": "Garde-corps", "library.railing_lead": "Garde-corps en verre solaire pour balcons et terrasses.", "library.structure": "Structures supplémentaires", "library.structure_lead": "Produits en verre solaire et auvent pour les structures sélectionnées.",
    "products.library_title": "Choisir les produits solaires", "products.library_lead": "Utilisez la bibliothèque par type de surface. Les choix de toiture, façade, vitrage, garde-corps et structures sont indépendants et ne s'écrasent pas.", "products.library_label": "Bibliothèque de surfaces", "products.selected_count": "sélectionné", "products.choose_material": "Choisir un matériau", "products.live_model": "Étude de conception en direct", "products.live_model_help": "Cliquez sur une surface dans l'étude 3D pour ouvrir sa bibliothèque correspondante.", "products.next_review": "Suivant : réviser et simuler"
  }
};
for (const [language, values] of Object.entries(additions)) {
  const file = path.join(root, `${language}.json`);
  const dictionary = JSON.parse(fs.readFileSync(file, "utf8"));
  Object.assign(dictionary, values);
  fs.writeFileSync(file, `${JSON.stringify(dictionary, null, 2)}\n`);
}
